#cloud-config
ssh_pwauth: True
chpasswd:
  list: |
     root:${rootpassword}
  expire: False

users:
  - name: test
    gecos: test user
    homedir: /home/test
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    lock_passwd: false
    # Hashed password to be used below generated by `mkpasswd --method=SHA-512 --rounds=4096
    passwd: $6$rounds=4096$Q.PRDIA9G8XZ0OTk$DlCrWE/umfTCg2b/EE1SEdMuSBUc9ekJg9j..MDzoPg8tAB4kFbJhlTb0EtbyXyj5.40Wp5bLe8Tba/HJy5IS/
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII6Lt79P3Lqw9J/K/PJXdNTcfX0OHUHDAH3X5u8sV25V


# Automatically resize the root partition and filesystem
growpart:
  mode: auto
  devices: ["/"]
  ignore_growroot_disabled: false

runcmd:
  - [ "resize2fs", "/dev/vda1" ]